# Subhan Khalid
P200086_BSCS-5A

In [1]:
class Matrix: 
 
    def __init__(self, dims, fill):    
        self.rows = dims[0]  
        self.cols = dims[1]   
        
        self.A = [
            [fill] * self.cols             
            for i in range(self.rows)
        ]

In [2]:
m = Matrix((3, 4), 2.0)


In [3]:
print(m)

In [4]:
def __str__(self):     
    rows = len(self.A)
    ret = ''     
    
    for i in range(rows):
        cols = len(self.A[i]) 
        
        for j in range(cols): 
            ret += str(self.A[i][j]) + "\t"
        ret += "\n"

    return ret


Matrix.__str__ = __str__ 

In [5]:
print(m)

2.0	2.0	2.0	2.0	
2.0	2.0	2.0	2.0	
2.0	2.0	2.0	2.0	



In [6]:
%time n = Matrix((100, 100), 0.0)

CPU times: user 117 µs, sys: 0 ns, total: 117 µs
Wall time: 124 µs


In [7]:
#Memory Usage
from sys import getsizeof
print(getsizeof(m))
print(getsizeof(n))

56
56


In [ ]:
!pip install pympler

In [8]:
from pympler.asizeof import asizeof

In [9]:
asizeof(m), asizeof(n)

(808, 87704)

In [10]:
dim = 5000

In [11]:
%time  m = Matrix((dim, dim), 0.0)

CPU times: user 550 ms, sys: 99.5 ms, total: 649 ms
Wall time: 649 ms


In [12]:
size = asizeof(m) / (1024 * 1024)

print("{:.2f} MBs".format(size))

191.08 MBs


In [13]:
def get(self, i, j): 
    
    # Error checking 
    if i < 0 or i > self.rows: 
        raise ValueError("Row index out of range.")
    if j < 0 or j > self.cols: 
        raise ValueError("Column index out of range.")
    
    # Value return
    return self.A[i][j]

Matrix.get = get

In [14]:
m.get(1, 2)

0.0

In [15]:
m.get(15, 0)

0.0

In [16]:
m.get(1, 10)

0.0

In [17]:
class Matrix: 
 
    def __init__(self, dims):    
        self.rows = dims[0]  
        self.cols = dims[1]   
        self.vals = {} 

In [18]:
def set(self, i, j, val): 
    self.vals[   (i, j)    ] = val 


Matrix.set = set 

In [19]:
def get(self, i, j): 
    
    if i < 0 or i > self.rows: 
        raise ValueError("Row index out of range.")
    if j < 0 or j > self.cols: 
        raise ValueError("Column index out of range.")
    
    
    if (i, j) in self.vals: 
        return self.vals[  (i, j)  ]
    
    return 0.0
    
Matrix.get = get

In [20]:
m = Matrix((5, 5))

In [21]:
print(m.vals)

{}


In [22]:
m.get(1, 1)

0.0

In [23]:
m.get(10, 2)

ValueError: Row index out of range.

In [24]:
m.set(1, 2, 15.0)

In [25]:
m.get(1, 2)

15.0

In [26]:
m.vals

{(1, 2): 15.0}

In [27]:
m.set(1, 4, 29.9)

In [28]:
m.get(1, 4)

29.9

In [29]:
dim = 500
m = Matrix((dim, dim))

In [30]:
asizeof(m)


608

In [31]:
#NUMPY

In [32]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [33]:
import numpy as np

In [34]:
np.random.seed(1337)

In [35]:
x = np.array(  [1, 4, 3]  )
x

array([1, 4, 3])

In [36]:
y = np.array([ [1, 4, 3], 
               [9, 2, 7] ] )
y

array([[1, 4, 3],
       [9, 2, 7]])

In [37]:
x.shape

(3,)

In [38]:
y.shape

(2, 3)

In [39]:
z = np.array(  [ [1, 4, 3] ]  )

In [40]:
z.shape

(1, 3)

In [41]:
z = np.arange(1, 2000, 1) 
z[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
z.shape

(1999,)

In [43]:
np.arange(0.5, 3, 0.5)


array([0.5, 1. , 1.5, 2. , 2.5])

In [44]:
np.arange(0.5, 10, 1).shape


(10,)

In [45]:
np.arange(0.5, 10, 1).reshape(5, 2).shape


(5, 2)

In [46]:
np.arange(0.5, 10, 1).reshape(5, 3).shape

ValueError: cannot reshape array of size 10 into shape (5,3)

In [47]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [48]:
print(x)
print(x[1]) 
print(x[1:])

[1 4 3]
4
[4 3]


In [49]:
print(y)
y[0, 1] 

[[1 4 3]
 [9 2 7]]


4

In [50]:
y[:, 1]

array([4, 2])

In [51]:
y[:, [1, 2]]

array([[4, 3],
       [2, 7]])

In [52]:
np.zeros((3, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [55]:
a.shape

(6,)

In [56]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [57]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

In [58]:
a[1:4] = [9, 8, 7]
a

array([1, 9, 8, 7, 5, 6])

In [59]:
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 1] = 4
b

array([[1., 2.],
       [0., 4.]])

In [60]:
b.shape

(2, 2)

In [61]:
print(b)

[[1. 2.]
 [0. 4.]]


In [62]:
b + 2

array([[3., 4.],
       [2., 6.]])

In [63]:
2 * b

array([[2., 4.],
       [0., 8.]])

In [64]:
b ** 2

array([[ 1.,  4.],
       [ 0., 16.]])

In [65]:
sum(b)

array([1., 6.])

In [66]:
b.sum()

7.0

In [67]:
b

array([[1., 2.],
       [0., 4.]])

In [68]:
b.sum(axis=0).shape

(2,)

In [69]:
b.sum(axis=1).shape

(2,)

In [70]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [71]:
print(b) 
print(d)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [72]:
b + d 

array([[ 4,  6],
       [ 8, 10]])

In [73]:
b * d

array([[ 3,  8],
       [15, 24]])

In [74]:
b.dot(d)

array([[13, 16],
       [29, 36]])

In [75]:
b ** d 

array([[   1,   16],
       [ 243, 4096]])

In [76]:
b.T

array([[1, 3],
       [2, 4]])

In [77]:
a

array([1, 9, 8, 7, 5, 6])

In [78]:
a.shape

(6,)

In [79]:
a.T

array([1, 9, 8, 7, 5, 6])

In [80]:
a.T.shape

(6,)

In [81]:
a.reshape(6,1).T.shape

(1, 6)

In [82]:
print(np.sqrt(36))

x = [1, 4, 9, 16]
np.sqrt(x)

6.0


array([1., 2., 3., 4.])

In [83]:
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [84]:
x > 3 

array([False, False,  True,  True,  True, False])

In [85]:
x > y 

array([ True, False,  True,  True,  True, False])

In [86]:
import math
def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    s = 1./(1. + math.e ** (-x))
    
    return s

In [87]:
basic_sigmoid(-1)


0.2689414213699951

In [88]:
basic_sigmoid(0)


0.5

In [89]:
x = [-1, 0, 3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [90]:
import numpy as np

x = [-1, 0, 3]
x = np.array(x)
basic_sigmoid(x)

array([0.26894142, 0.5       , 0.95257413])